# Site settings
title: Ayshan Safarova
name: Ayshan Safarova

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/ayshansafarova
 - title: LinkedIn
   url: https://www.linkedin.com/in/ayshansafarova/

#Any buzzword skills you want to include
skills:
 - C#
 - .Net 
 - ASP.Net MVC
 - React
 - Firebase
 - Javascript
 - Jquery
 - Webpack
 - Chart.js
 - Bootstrap 
 - HTML
 - CSS
 - PL/SQL
 - PHP
 - Selenium Testing 
 - SignalR

#Work experience is required
roles:
 - title: Web Developer Intern
   start: April, 2018
   end: July, 2018
   employer: Crocusoft
   description: Project: https://edp.az/ 
 - title: Developer&Designer
   start: August, 2018
   end: December, 2018
   employer: Mammadoff Creative Agency
   description: Project: https://otos.az/
   

#Education is required
education:
 - level: Bachelor of Engineering
   date: September, 2015
   subject: Computer Engineering
   school: Baku Engineering University

#List of interesting Github repo/projects to include - optional
github:
 - ayshansafarova/MeetingApp
 - ayshansafarova/BakuBike
 - ayshansafarova/webpack-template
 - ayshansafarova/chart.js-task
 - ayshansafarova/FirstReactJs
 - ayshansafarova/FirstReactMobileApp
 - ayshansafarova/mass-effect-3
 - ayshansafarova/SimpleCalculator
 - ayshansafarova/desktop-Apps
 - ayshansafarova/Snake
 - ayshansafarova/Ex-php
 - ayshansafarova/console_app
 - ayshansafarova/Hospital-
 - ayshansafarova/VirtualCard
 - ayshansafarova/Line-Circle-Ellipse
 - ayshansafarova/SpeechText
 - ayshansafarova/client_server
 - ayshansafarova/BouncingBall
 - ayshansafarova/FragmentAndroid
 - ayshansafarova/InternalStorage
